export const SET_LOGIN = "SET_LOGIN";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCES";
export const SET_LOGIN_FAILURE = "SET_LOGIN_FAILURE";
export const SET_LOGIN_TOKEN = "SET_LOGIN_TOKEN";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_CLIENT_DETAILS = "SET_CLIENT_DETAILS";
export const SET_RESTAURANT_DETAILS = "SET_RESTAURANT_DETAILS";
