export const SET_TABLES = "SET_TABLES";
export const SET_TABLES_SUCCESS = "SET_TABLES_SUCCESS";
export const SET_TABLES_FAILURE = "SET_TABLES_FAILURE";
export const SET_TABLE_RESET = "SET_TABLE_RESET";